In [2]:
import pandas as pd
full_df = pd.read_csv('full_df.csv')

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances

import nltk
from nltk.tag import pos_tag
from nltk import word_tokenize
from nltk.corpus import stopwords
stop = stopwords.words('english')
def cleaning_text(sentence):
    sentence = str(sentence)
    sentence=sentence.lower()
    sentence=re.sub('[^\w\s]',' ', sentence) #removes punctuations
    sentence=re.sub('_',' ', sentence) #removes punctuations
    sentence=re.sub('\d+',' ', sentence) #removes digits
    cleaned=' '.join([w for w in sentence.split() if not w in stop]) # removes english stopwords
    cleaned=' '.join([w for w , pos in pos_tag(cleaned.split()) if (pos == 'NN' or pos=='JJ' or pos=='JJR' or pos=='JJS' )])
    
#selecting only nouns and adjectives
    cleaned=' '.join([w for w in cleaned.split() if not len(w)<=2 ]) #removes single lettered words and digits
    cleaned=cleaned.strip()
    return cleaned
	  
full_df['cleaned'] = full_df['Description'].apply(lambda x: cleaning_text(x))


data_high=full_df.loc[(full_df['Interest_Level']=='high')]
data_medium=full_df.loc[(full_df['Interest_Level']=='medium')]
data_low=full_df.loc[(full_df['Interest_Level']=='low')]

binVectorizer = CountVectorizer(binary=True)
counts = binVectorizer.fit_transform(full_df['cleaned'])

In [9]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
targets = full_df['Interest_Level'].values
classifier.fit(counts, targets)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [18]:
examples = full_df['cleaned']
example_counts = binVectorizer.transform(examples)
predictions = classifier.predict(example_counts)
predictions_df=pd.DataFrame(predictions)
predictions_df.head(10)
actual=full_df['Interest_Level'].values
from sklearn.metrics import confusion_matrix
matrix=pd.DataFrame(confusion_matrix(actual, predictions,labels=["low", "medium", "high"]))
#print(matrix)

#pd.crosstab(full_df['Interest_Level'], predictions, rownames=['True'], colnames=['Predicted'], margins=True)
#predictions
import numpy as np
import pandas as pd
import scipy.sparse as sparse

full_df['Predicted_des'] = predictions.tolist()

       0     1    2
0  28883  4413  988
1   5536  5229  464
2   1732  1238  869

In [19]:
full_df.to_csv('example.csv')

,Unnamed: 0,Apartment,Bathrooms,Bedrooms,Building_ID,Date_Created,Description,Address,latitude,longitude,...,Date_Created.Year,Date_Created.Date,Date_Created.WDayLbl,Date_Created.Week,Date_Created.Quarter,Date_Created.Hour,Date_Created.WeekofMonth,Date_Created.YDay,cleaned,Predicted_des
0,1,10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:00,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,40.7145,-73.9425,...,2016,2016-06-24,Fri,26,2,7,4,176,brand new bedroom bath apartmentenjoy apartmen...,medium
1,2,10000,1.0,2,c5c8a357cba207596b04d1afd1e4f130,2016-06-12 12:19:00,,Columbus Avenue,40.7947,-73.9667,...,2016,2016-06-12,Sun,24,2,12,2,164,,low
2,3,100004,1.0,1,c3ba40552e2120b0acfc3cb5730bb2aa,2016-04-17 03:26:00,"Top Top West Village location, beautiful Pre-w...",W 13 Street,40.7388,-74.0018,...,2016,2016-04-17,Sun,16,2,3,3,108,top top west village location beautiful pre wa...,low
3,4,100007,1.0,1,28d9ad350afeaab8027513a3e52ac8d5,2016-04-18 02:22:00,Building Amenities - Garage - Garden - fitness...,East 49th Street,40.7539,-73.9677,...,2016,2016-04-18,Mon,16,2,2,3,109,building garden fitness room laundry room roof...,low
4,5,100013,1.0,4,NaN,2016-04-28 01:32:00,Beautifully renovated 3 bedroom flex 4 bedroom...,West 143rd Street,40.8241,-73.9493,...,2016,2016-04-28,Thu,17,2,1,4,119,bedroom flex bedroom apartment rent available ...,low
5,6,100014,2.0,4,38a913e46c94a7f46ddf19b756a9640c,2016-04-19 04:24:00,,West 18th Street,40.7429,-74.0028,...,2016,2016-04-19,Tue,16,2,4,3,110,,low
6,7,100016,1.0,2,3ba49a93260ca5df92fde024cb4ca61f,2016-04-27 03:19:00,Stunning unit with a great location and lots o...,West 107th Street,40.8012,-73.9660,...,2016,2016-04-27,Wed,17,2,3,4,118,unit great location natural close subway line ...,low
7,8,100020,2.0,1,0372927bcb6a0949613ef5bf893bbac7,2016-04-13 06:01:00,"This huge sunny ,plenty of lights 1 bed/2 bath...",West 21st Street,40.7427,-73.9957,...,2016,2016-04-13,Wed,15,2,6,2,104,huge sunny plenty bath brand new kitchen open ...,low
8,9,100026,1.0,1,a7efbeb58190aa267b4a9121cd0c88c0,2016-04-20 02:36:00,<p><a website_redacted,Hamilton Terrace,40.8234,-73.9457,...,2016,2016-04-20,Wed,16,2,2,3,111,website,low
9,10,100027,2.0,4,NaN,2016-04-02 02:58:00,This is a spacious four bedroom with every bed...,522 E 11th,40.7278,-73.9808,...,2016,2016-04-02,Sat,14,2,2,1,93,spacious bedroom bedroom able fit queen room s...,low
10,11,100030,1.0,0,NaN,2016-04-14 01:10:00,New to the market! Spacious studio located in ...,York Avenue,40.7769,-73.9467,...,2016,2016-04-14,Thu,15,2,1,2,105,new market spacious studio elevator laundry ro...,low
11,12,10004,1.0,1,NaN,2016-06-03 03:21:00,Check out this one bedroom apartment in a grea...,W. 173rd Street,40.8448,-73.9396,...,2016,2016-06-03,Fri,23,2,3,1,155,bedroom apartment great location washington ap...,low
12,13,100044,1.0,2,67c9b420da4a365bc26a6cd0ef4a5320,2016-04-19 05:37:00,***LOW FEE. Beautiful CHERRY OAK WOODEN FLOORS...,E 38th St,40.7488,-73.9770,...,2016,2016-04-19,Tue,16,2,5,3,110,low fee beautiful wooden floorsthe lobby nice ...,medium
13,14,100048,2.0,2,NaN,2016-04-09 01:22:00,Lincoln Square's premier full service building...,West 63rd Street,40.7707,-73.9817,...,2016,2016-04-09,Sat,15,2,1,2,100,lincoln square full service short distance cen...,medium
14,15,10005,1.0,1,NaN,2016-06-01 03:11:00,Spacious 1-Bedroom to fit King-sized bed comfo...,East 56th St..,40.7584,-73.9648,...,2016,2016-06-01,Wed,22,2,3,1,153,spacious bedroom fit bed pristine marble bathr...,low
15,16,100051,1.0,0,bfb9405149bfff42a92980b594c28234,2016-04-18 02:36:00,Stunning full renovated studio unit. High cei...,East 34th Street,40.7439,-73.9743,...,2016,2016-04-18,Mon,16,2,2,3,109,full studio unit high sleek oak strip spacious...,low
16,17,100052,1.0,2,642cc2c920512ffe2a74c28122f8b47f,2016-04-22 05:57:00,East Village is a great community with great p...,1st Ave.,40.7305,-73.9830,...,2016,2016-04-22,Fri,17,2,5,4,113,east village great community great good great ...,low
17,18,100053,1.0,1,NaN,2016-04-19 03:36:00,"*Location: Thayer St. &amp; Broadway, Manhatta...",Thayer St,40.8643,-73.9280,...,2016,2016-04-19,Tue,16,2,3,3,110,location thayer manhattan large bedroom apartm...,low
18,19,100055,1.0,4,cc4c6ae9225df6d2395c4e16c235f7ab,2016-04-20 04:00:00,,West 106th Street,40.7999,-73.9638,...,2016,2016-04-20,Wed,16,2,4,3,111,,low
19,20,100058,1.0,1,dc3cae15729b48fec3394f9295671991,2016-04-09 03:49:00,,1st Avenue,40.7328,-73.9799,...,2016,2016-04-09,Sat,15,2,3,2,100,,low
20,21,100062,1.0,3,205f95d4a78f1f3befda48b89edc9669,2016-04-12 02:39:00,BEAUTIFUL 2 BEDROOM POSSIBLE CONVERSION INTO T...,Madison Avenue,40.7454,-73.9845,...,2016,2016-04-12,Tue,15,2,2,2,103,beautiful bedroom possible conversion bedroom ...,low
21,22,100063,1.0,2,ecea86b79afa539505aa4bad3ff449c6,2016-04-07 02:11:00,No fee huge two bedroom apartment. Great locat...,"E 30th St,",40.7427,-73.9794,...,2016,2016-04-07,Thu,14,2,2,1,98,fee huge bedroom apartment great location nyu ...,low
22,23,100065,1.0,1,1a6cf9b71da65cdc0cfd5015a75317ac,2016-04-13 05:17:00,,East 35th Street,40.7447,-73.9741,...,2016,2016-04-13,Wed,15,2,5,2,104,,low
23,24,100066,1.0,1,a6200d7448037cfee809b2451219f879,2016-04-17 02:26:00,CooperCooper.com :: Web ID #179546; Access 100...,Liberty Street,40.7074,-74.0081,...,2016,2016-04-17,Sun,16,2,2,3,108,coopercooper com web access unique apartment d...,low
24,25,10007,2.0,4,05b871a1e1e0368391160bcefc608e00,2016-06-07 04:39:00,SPRAWLING 2 BEDROOM FOUND! ENJOY THE LUXURY OF...,W 18 St.,40.7391,-73.9936,...,2016,2016-06-07,Tue,23,2,4,1,159,bedroom enjoy luxury full service doorman resi...,medium
25,26,100071,3.5,4,45b4143a9841eb63d7203c4f21a64ff7,2016-04-27 06:43:00,Amazing 4 bedroom convertible. Remarkably luxu...,East 56th,40.7584,-73.9653,...,2016,2016-04-27,Wed,17,2,6,4,118,bedroom convertible luxurious high floor incre...,low
26,27,100075,1.0,1,d68497ff1f5ac77f143e5f21817ed6fb,2016-04-25 02:29:00,Don't miss out on this fantastic apartment.......,E 81st St.,40.7728,-73.9502,...,2016,2016-04-25,Mon,17,2,2,4,116,miss fantastic apartment spacious bdr affordab...,low
27,28,100076,1.0,1,ec447453d3b8033e14a7b54ba1e13e02,2016-04-22 05:39:00,The TRUE 1 bedroom apartment features extra la...,West 57th Street,40.7709,-73.9917,...,2016,2016-04-22,Fri,17,2,5,4,113,true bedroom apartment extra large light day s...,low
28,29,100079,1.0,1,f06ad2f6f1a821c8efc03dc195d369df,2016-04-21 05:27:00,"Currently under renovation, this one b...",1215 Morris Avenue,40.8335,-73.9141,...,2016,2016-04-21,Thu,16,2,5,3,112,bedroom beautiful call text personal tour today,low
29,30,100081,2.0,2,f115a9bff3a9c4e6eedc9114374b3d74,2016-04-26 02:59:00,Gut Renovated Apartment with Stainless steel a...,E 79th St.,40.7716,-73.9506,...,2016,2016-04-26,Tue,17,2,2,4,117,gut apartment stainless steel natural maple sh...,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49322,49323,99915,1.0,1,NaN,2016-04-25 01:13:00,"Elegant, spacious one bedroom in modern luxury...",North 10th Street,40.7176,-73.9531,...,2016,2016-04-25,Mon,17,2,1,4,116,elegant spacious bedroom modern luxury buildin...,low
49323,49324,99917,1.0,1,e243886a4cac69881c07c6a1f38185bf,2016-04-26 04:43:00,NaN,W 58th St,40.7655,-73.9785,...,2016,2016-04-26,Tue,17,2,4,4,117,nan,low
49324,49325,99919,1.0,0,da2f861e30b1391e8368438efddaa2a7,2016-04-08 05:51:00,(((((IMPORTANT NOTICE))))) If you are planning...,East 78th Street,40.7721,-73.9539,...,2016,2016-04-08,Fri,15,2,5,2,99,important notice next urgent subject email sta...,medium
49325,49326,99921,1.0,2,fc0676a4d4fdb4e767faf6414975a0cb,2016-04-29 15:03:00,WASHER & DRYER IN UNIT ++ 5 MINUTE WALK TO R T...,Ridge Blvd.,40.6182,-74.0360,...,2016,2016-04-29,Fri,18,2,15,5,120,dryer unit minute walk train bright sunny larg...,medium
49326,49327,99923,2.0,2,NaN,2016-04-05 01:12:00,Tremendous Classic Six in a Luxurious Prewar D...,West 81st Street,40.7829,-73.9731,...,2016,2016-04-05,Tue,14,2,1,1,96,tremendous classic luxurious prewar doorman we...,low
49327,49328,99924,1.0,1,93cd24891f8423d45ac587ab1fdb1225,2016-04-24 03:15:00,Luxury Living--- Full-Time Doorman--- Concierg...,8th Avenue,40.7637,-73.9847,...,2016,2016-04-24,Sun,17,2,3,4,115,luxury full time doorman concierge prime midto...,low
49328,49329,99931,1.0,1,NaN,2016-04-25 01:20:00,Only one block form Washington Square Park! Ne...,Thompson Street,40.7293,-73.9987,...,2016,2016-04-25,Mon,17,2,1,4,116,block form washington square park new gut reno...,low
49329,49330,99933,1.0,2,80a120d6bc3aba97f40fee8c2204524b,2016-04-03 03:51:00,THIS RESIDENCE FEATURES STAINLESS STEAL APPLI...,Water,40.7075,-74.0043,...,2016,2016-04-03,Sun,14,2,3,1,94,residence stainless steal new hardwood open bl...,low
49330,49331,99935,1.0,1,NaN,2016-04-19 02:58:00,This newly renovated 1 bedroom unit is recentl...,East 12th Street,40.7287,-73.9808,...,2016,2016-04-19,Tue,16,2,2,3,110,bedroom unit ton natural light new market prim...,low
49331,49332,99937,1.5,0,d48767c37a934daaf0bbb0e58c755d0c,2016-04-14 05:39:00,"Bedroom on top, Living room on bottom<br /><br...",York Avenue,40.7769,-73.9467,...,2016,2016-04-14,Thu,15,2,5,2,105,bedroom top living room bottom spacious opport...,low
49332,49333,9994,1.0,2,NaN,2016-06-06 01:22:00,Don't miss out on this spacious and beautiful ...,West 98th Street,40.7957,-73.9705,...,2016,2016-06-06,Mon,23,2,1,1,158,spacious beautiful upper west side bedroom pre...,low
49333,49334,99953,1.0,1,e243886a4cac69881c07c6a1f38185bf,2016-04-26 02:18:00,"This exquisitely appointed 1 bedroom, 1 bath r...",West 58th Street,40.7655,-73.9785,...,2016,2016-04-26,Tue,17,2,2,4,117,bedroom bath residence time square area enjoy ...,low
49334,49335,99956,2.0,2,NaN,2016-04-16 16:39:00,This spacious two bedroom apartment features e...,Nassau Street,40.7095,-74.0084,...,2016,2016-04-16,Sat,16,2,16,3,107,spacious bedroom apartment energy efficient so...,low
49335,49336,99960,1.0,1,6f1e2020bd0e4ff48d3a5d482944a753,2016-04-05 04:35:00,Great Lower East Side one bedroom.Well maintai...,Baxter Street,40.7179,-73.9989,...,2016,2016-04-05,Tue,14,2,4,1,96,great lower east side bedroom prewar building ...,low
49336,49337,99961,2.0,3,ae3e5e3d93ea18140752078f9a3177af,2016-04-22 03:11:00,THIS LARGE AND SPACIOUS 3 BD/ONE BA APARTMENT ...,East 3rd Street,40.7222,-73.9824,...,2016,2016-04-22,Fri,17,2,3,4,113,large spacious apartment hardwood brick granit...,medium
49337,49338,99964,1.0,0,f8009151babfad197b48f6922eec99f2,2016-04-29 05:20:00,77TH ST! FULLY GUT RENOV STUDIO! HI CEIL! XPSD...,E 77 St,40.7708,-73.9525,...,2016,2016-04-29,Fri,18,2,5,5,120,gut renov studio ceil brick amazing studio mar...,medium
49338,49339,99965,2.0,3,a485c2deb62ad3c9c76edebd532a446c,2016-04-03 05:23:00,Full-Time Doorman PET FRIENDLYElevator GYMLaun...,East 87th Street,40.7766,-73.9463,...,2016,2016-04-03,Sun,14,2,5,1,94,full time doorman pet friendlyelevator gymlaun...,low
49339,49340,99966,1.0,3,a36895b9975c6991ca0fa1d9a99023a1,2016-04-15 05:36:00,This is a Great Opportunity to Rent an Excelle...,East 72nd Street,40.7695,-73.9603,...,2016,2016-04-15,Fri,16,2,5,3,106,great opportunity rent excellent bed flexed be...,low
49340,49341,99979,1.0,1,e4490b8e6a410d39d38e40e572243a64,2016-04-14 03:32:00,,Eldert St,40.6865,-73.9134,...,2016,2016-04-14,Thu,15,2,3,2,105,,low
49341,49342,99980,1.0,0,d16f875956b264d5920d8424631091d4,2016-04-27 12:52:00,Incredibly sunny and spacious studio apartment...,John Street,40.7090,-74.0105,...,2016,2016-04-27,Wed,17,2,12,4,118,spacious studio apartment luxury high rise hou...,low
49342,49343,99982,1.0,1,6134e7c4dd1a98d9aee36623c9872b49,2016-04-07 02:29:00,"LUXURY BUILDING IN MIDTOWN WEST, 24 HR DOORMAN...",W 54 St.,40.7645,-73.9840,...,2016,2016-04-07,Thu,14,2,2,1,98,luxury midtown west doorman close transportati...,low
49343,49344,99984,1.0,1,8e7bd3cbdd67a0dcc719224a41699d2b,2016-04-02 03:17:00,Huge true king size one bedroom in an elevator...,E 76 Street,40.7728,-73.9591,...,2016,2016-04-02,Sat,14,2,3,1,93,huge true size bedroom elevator new kitchen di...,low
49344,49345,99986,1.0,1,399f92c2a78ada2f01c8414ce3bc909b,2016-04-14 03:39:00,"Charming one bedroom! Hardwood floors, sunny, ...",Charles Street,40.7350,-74.0007,...,2016,2016-04-14,Thu,15,2,3,2,105,bedroom hardwood sunny spacious space miss ama...,low
49345,49346,99987,1.0,1,NaN,2016-04-11 03:29:00,**89th & Park Ave! (block from the central par...,East 89th Street,40.7889,-73.9719,...,2016,2016-04-11,Mon,15,2,3,2,102,park central park huge kitchen space next subw...,low
49346,49347,99988,1.0,1,3b13a6597596619bdbc8281096f21d23,2016-04-22 15:44:00,24hr Doorman Luxury building in the heart of t...,East 10th Street,40.7296,-73.9869,...,2016,2016-04-22,Fri,17,2,15,4,113,doorman luxury heart east village building roo...,low
49347,49348,9999,1.0,2,297160caf8a88c10718b492d4672c6b4,2016-06-02 05:41:00,"30TH/3RD, MASSIVE CONV 2BR IN LUXURY FULL SERV...",E 30 St,40.7426,-73.9790,...,2016,2016-06-02,Thu,22,2,5,1,154,massive conv luxury full service heart murray ...,medium
49348,49349,99991,1.0,1,9e871ccfea7b07686c101548ca693af6,2016-04-04 18:22:00,"HIGH END condo finishes, swimming pool, and ki...",Rector Pl,40.7102,-74.0163,...,2016,2016-04-04,Mon,14,2,18,1,95,high end condo pool bed spacious sunny bedroom...,medium
49349,49350,99992,1.0,1,7967a1280bf3f7644500fc79d2696b0e,2016-04-16 02:13:00,Large Renovated One Bedroom Apartment with Sta...,West 45th Street,40.7601,-73.9900,...,2016,2016-04-16,Sat,16,2,2,3,107,large bedroom apartment stainless steel doorma...,low
49350,49351,99993,1.0,0,ad67f6181a49bde19218929b401b31b7,2016-04-08 02:13:00,Stylishly sleek studio apartment with unsurpas...,Wall Street,40.7066,-74.0101,...,2016,2016-04-08,Fri,15,2,2,2,99,sleek studio apartment unsurpassed modern manh...,low
49351,49352,99994,1.0,2,5173052db6efc0caaa4d817112a70f32,2016-04-12 02:48:00,Look no further!!! This giant 2 bedroom apart...,Park Terrace East,40.8699,-73.9172,...,2016,2016-04-12,Tue,15,2,2,2,103,look giant bedroom apartment inwood manhattan ...,low